config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root "links#index"
	resources :links do
		resources :comments
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :link

	validates :body, presence: true
end

app/models/link.rb
class Link < ApplicationRecord
	validates :title, presence: true
	validates :url, presence: true

	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
	has_many :links
	has_many :comments
		
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_link
	before_action :find_comment, only: [:edit, :update, :destroy]
	before_action :authenticate_user!

	def create
		@comment = @link.comments.create(comment_param)
		@comment.user_id = current_user.id

		if @comment.save
			flash[:success] = "Successfuly added a comment"
			redirect_to @link
		else
			flash[:alert] = 'Comment was empty!'
			redirect_to @link
		end
	end	

	def edit
	end

	def update
		if @comment.update(comment_param)
			flash[:success] = "Successfuly edited a comment"
			redirect_to @link
		else
			flash[:alert] = "Something was wrong"
			render "edit"
		end
	end

	def destroy
		@comment.destroy
		flash[:success] = "Successfuly deleted a comment"
		redirect_to @link
	end


	private
		def comment_param
			params.require(:comment).permit(:body)
		end

		def find_link
			@link = Link.find(params[:link_id])
		end

		def find_comment
			@comment = @link.comments.find(params[:id])
		end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
	before_action :find_link, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@links = Link.all.order('created_at DESC')		
	end

	def new
		@link = current_user.links.build
	end

	def create
		@link = current_user.links.build(link_params)

		if @link.save
			flash[:success] = "Successfuly added a new link"
			redirect_to @link
		else
			render "new"
		end
	end

	def show
	end

	def edit
	end

	def update
		if @link.update(link_params)
			flash[:success] = "Successfuly edited a new link"
			redirect_to link_path(@link)
		else
			render "edit"
		end
	end
	
	def destroy
		@link.destroy
		flash[:success] = 'Successfuly deleted link'
		redirect_to root_path
	end

	private
		def link_params
			params.require(:link).permit(:title, :url, :description)
		end

		def find_link
			@link = Link.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/comments/_comment.html.haml
%h5
	Created by: 
	=comment.user.email
%small= time_ago_in_words(comment.created_at)
%p= comment.body
-if user_signed_in? && comment.user_id = current_user.id
	=link_to("Edit", edit_link_comment_path(comment.link, comment))
	=link_to("Delete", link_comment_path(comment.link, comment), method: :delete, data: {confirm: "Are you sure?"})
%hr/

app/views/comments/_form.html.haml
=simple_form_for([@link, @link.comments.build]) do |f|
	=f.input :body, as: :text, label: false
	=f.button :submit

app/views/comments/edit.html.haml
%h1 Edit Comment:
=simple_form_for([@link, @comment]) do |f|
	=f.input :body, as: :text, require: true
	=f.button :submit

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
	%head
		%title RedditClone
		=csrf_meta_tags
		=stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
		=javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
	%body
		%header.navbar.navbar-default
			.container
				%a.navbar-brand{href: root_path} Reddit Clone
				
				%ul.navbar-left.nav.navbar-nav
					-if user_signed_in?
						%li
							=link_to("Sign out", destroy_user_session_path, method: :delete)
					-else
						%li
							=link_to("Sign up", new_user_registration_path)
						%li
							=link_to("Sign in", new_user_session_path)
				-if user_signed_in?
					%ul.navbar-right.nav.navbar-nav
						%li
							=link_to("Add link", new_link_path)

		.container
			-if !flash.empty?
				-flash.each do |type, msg|
					%p{class: type}
						=msg
			=yield

app/views/links/_form.html.haml
=simple_form_for @link do |f|
	=f.input :title
	=f.input :url
	=f.input :description, as: :text
	=f.button :submit

app/views/links/edit.html.haml
%h1 Edit link
=render "form"

app/views/links/index.html.haml
%h1 Check the newest, intresting links: 

-@links.each do |link|
	%hr/
	%h3
		=link_to(link.title, link)
	%p= link.description
	%small
		Created at
		=time_ago_in_words(link.created_at)
		ago

app/views/links/new.html.haml
%h1 New link
=render 'form'

app/views/links/show.html.haml
%h1= @link.title
%small
	Created at
	=time_ago_in_words(@link.created_at)
	ago
%br
=link_to(@link.url, @link.url)
-if user_signed_in? && @link.user_id == current_user.id
	%p
		=link_to("Edit", edit_link_path(@link), class: "btn btn-warning")
		=link_to("Delete", @link, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger")
%hr/
%h3 Description: 
%p= @link.description
%hr/
%h3 Comments: 
=render @link.comments
%hr/
%h3 Add new comment:
=render 'comments/form'